<?php
/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace APIBuzonesLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Data5 implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $id public property
     */
    public $id;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $leido public property
     */
    public $leido;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $borrado public property
     */
    public $borrado;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $fecha public property
     */
    public $fecha;

    /**
     * @todo Write general description for this property
     * @required
     * @var \APIBuzonesLib\Models\Data6 $data public property
     */
    public $data;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $id      Initialization value for $this->id
     * @param bool   $leido   Initialization value for $this->leido
     * @param bool   $borrado Initialization value for $this->borrado
     * @param string $fecha   Initialization value for $this->fecha
     * @param Data6  $data    Initialization value for $this->data
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->id      = func_get_arg(0);
            $this->leido   = func_get_arg(1);
            $this->borrado = func_get_arg(2);
            $this->fecha   = func_get_arg(3);
            $this->data    = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']      = $this->id;
        $json['leido']   = $this->leido;
        $json['borrado'] = $this->borrado;
        $json['fecha']   = $this->fecha;
        $json['data']    = $this->data;

        return $json;
    }
}
