<?php
/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace APIBuzonesLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ModificarUnMensajeLeidoBorradoRequest implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var bool $leido public property
     */
    public $leido;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $borrado public property
     */
    public $borrado;

    /**
     * Constructor to set initial or default values of member properties
     * @param bool $leido   Initialization value for $this->leido
     * @param bool $borrado Initialization value for $this->borrado
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->leido   = func_get_arg(0);
            $this->borrado = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['leido']   = $this->leido;
        $json['borrado'] = $this->borrado;

        return $json;
    }
}
