<?php
/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace APIBuzonesLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ModificarUnGrupoPorNombreRequest implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $nombre public property
     */
    public $nombre;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $aplicacion public property
     */
    public $aplicacion;

    /**
     * @todo Write general description for this property
     * @required
     * @var array $usuarios public property
     */
    public $usuarios;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $nombre     Initialization value for $this->nombre
     * @param string $aplicacion Initialization value for $this->aplicacion
     * @param array  $usuarios   Initialization value for $this->usuarios
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->nombre     = func_get_arg(0);
            $this->aplicacion = func_get_arg(1);
            $this->usuarios   = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['nombre']     = $this->nombre;
        $json['aplicacion'] = $this->aplicacion;
        $json['usuarios']   = $this->usuarios;

        return $json;
    }
}
